[build]
  command = "node tools/write-config.js"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "https://geoscope-91wm.netlify.app/*"
    to = "https://geoscope.live/:splat"
      status = 301
        force = true
        
