#!/usr/bin/env node
/**
 * write-config.js — generates js/config.js from environment variables so that no
 * project-specific value has to be committed:
 *
 *   SUPABASE_URL=https://xxxx.supabase.co SUPABASE_ANON_KEY=eyJ... CREDIT_URL=https://... node tools/write-config.js
 *
 * Only the public anon key is accepted. If SUPABASE_SERVICE_ROLE_KEY is set the script
 * refuses to run, as a guard against shipping a privileged key to the browser.
 */
const fs = require('fs');
const path = require('path');

if (process.env.SUPABASE_SERVICE_ROLE_KEY) {
  console.error('Refusing to write config: SUPABASE_SERVICE_ROLE_KEY is set. The browser must only ever receive the anon key.');
  process.exit(1);
}
const url = (process.env.SUPABASE_URL || '').trim();
const key = (process.env.SUPABASE_ANON_KEY || '').trim();
const credit = (process.env.CREDIT_URL || '#').trim();

if (url && !/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(url)) {
  console.error('SUPABASE_URL must look like https://<project-ref>.supabase.co');
  process.exit(1);
}
if (key && !/^[A-Za-z0-9._-]{20,}$/.test(key)) {
  console.error('SUPABASE_ANON_KEY does not look like a valid key');
  process.exit(1);
}
if (credit !== '#' && !/^https:\/\/[^\s"'<>]+$/.test(credit)) {
  console.error('CREDIT_URL must be an https:// URL');
  process.exit(1);
}

if (!url) {
  console.log('No SUPABASE_URL in environment - keeping the committed js/config.js unchanged.');
  process.exit(0);
}

const out = '// Generated by tools/write-config.js — do not commit. Only the public anon key belongs here.\n' +
  'window.GEO_CONFIG = ' + JSON.stringify({ supabaseUrl: url, supabaseAnonKey: key, creditUrl: credit }, null, 2) + ';\n';
const target = path.join(__dirname, '..', 'js', 'config.js');
fs.writeFileSync(target, out);
console.log('wrote ' + target + (url ? '' : ' (Supabase disabled: no SUPABASE_URL)'));
